### PR TITLE
UI replacement WIP

### PR DESCRIPTION
**Pull request by jfmherokiller**
this pull request is equal to my original pull found here https://github.com/Kitteh6660/Corruption-of-Champions-Mod/pull/1148 

I am just updating it for this fork

### CODE REVIEW

**Comment by jfmherokiller** [comment]
just an immedate warning the UI will have bugs.

**Comment by jfmherokiller** [comment]
so far the only visual bug is at the begining extra ui components seem to appear but soon disappear once the buttons on the bottom show up.

**Comment by aimozg** [comment]
@jfmherokiller That would be great! But please update to target the `master-wip` branch - this is where current work happens, `master` is updated on major releases.

**Comment by jfmherokiller** [comment]
> @jfmherokiller That would be great! But please update to target the `master-wip` branch - this is where current work happens, `master` is updated on major releases.

will do i by default use master as the main branch

**Comment by jfmherokiller** [comment]
closing because used wrong branch

**Comment by jfmherokiller** [comment]
just rembered i can just pull the diffrence down

**Comment by jfmherokiller** [comment]
yep compiles and runs tho I do need QA help since code is fine but any issues are now visual.

**Comment by aimozg** [comment]
alright, will check

**Comment by aimozg** [comment]
broken things found so far:
[ ] new perk menu sizing, bg, and scrolling
[ ] hotkey binding pane bg
[ ] scrolling main text doesn't sync with scrollbar
[ ] predefined characters dropdown
[ ] racial paragon dropdown (all dropdowns I guess)

**Comment by jfmherokiller** [comment]
oh yes i think first ill go after the dropdowns

**Comment by jfmherokiller** [comment]
image
after a little bit of fixing this is what i have now in terms of drop downs

**Comment by jfmherokiller** [comment]
i also identified a "parasitic" dropdown element that seems to appear when dealing with the level up screens.

**Comment by jfmherokiller** [comment]
the broken background of the new perks menu seems to be from implementation defined behavior. I think i can figure out how to fix it just might take a bit.

**Comment by jfmherokiller** [comment]
After playing most of the game it seems the only thing left broken is the new perks menu.

**Comment by aimozg** [comment]
Can't you give it a transparent bg?

**Comment by jfmherokiller** [comment]
> Can't you give it a transparent bg?

no i actually just figured out the issue I was forgetting to set the background on the ScrollPane container of the perks menu.

**Comment by jfmherokiller** [comment]
image
fixed it

**Comment by jfmherokiller** [comment]
I like your transparency idea better tho so i am implementing that now

**Comment by jfmherokiller** [comment]
I think the UI remake is now "complete"

**Comment by aimozg** [comment]
Alright, I'll check it when I have time

**Comment by jfmherokiller** [comment]
I also want to say that I am attempting to see if the research/work i put into porting the other fork to html5 will work here. I was more or less attempting to provide a way to compile the game into html5 without the need for a complete rewrite in another programming language. I cant say if my research will bear fruit but I have an idea using apache royale.

**Comment by jfmherokiller** [comment]
are there any noteable bugs with the UI replacement or is it merge ready?

**Comment by aimozg** [comment]
Haven't had a chance to test properly; I'll check it this weekend.

**Comment by aimozg** [comment]
New perk menu doesn't scroll with mouse wheel. This is a blocker

And some cosmetic complaints:
* Combobox expander button doesn't have an arrow
* Please change combobox font and text color, gray fancy font is hard to read
* Perk menu has horizontal scrollbar
* Perk menu has extra border

**Comment by jfmherokiller** [comment]
I may need extra help fixing the other cosmetic requirements besides the font one.

**Comment by jfmherokiller** [comment]
i wanted to make sure it was kept up with master-wip to make it easier to merge

**Comment by aimozg** [comment]
Thanks for your work. I'll do the finishing touches.

**Comment by aimozg** [comment]
Should be ready to merge

**Pull request merged**
